#!/usr/bin/env python3
"""Training data for the one behaviour retrieval cannot fix: knowing when to stop.

The deployed system answers hand-written questions at 85.3%, and its weakest
family is questions whose premise is false -- a feat nobody wrote, a mechanic
from a different game. It invents an answer about one time in five.

The previous adapter failed at exactly this, and the failure is instructive. It
was trained on templated questions with templated answers, gained ten points on a
benchmark generated by the same templates, and lost three on questions written by
hand. So this recipe changes both halves:

**Questions are written by a model, in player language, and never templated.**

Answers are handled in two passes, because the first attempt at pure distillation
failed in an informative way: asked the same question the student gets, the 27B
teacher **refused only 2 of 31 times** on premises that were false by
construction. It invents an answer just as the 9B does, so there is nothing to
distil. Frontier-scale models behave the same way, and the literature agrees --
RefusalBench finds refusal accuracy below 50% across thirty models, with neither
scale nor reasoning helping.

So answerable items are distilled from the teacher answering the real retrieved
context, and refusal items are *guided*: the teacher is told the verdict, which is
correct by construction, and asked to phrase it naturally against the same
excerpts. The label comes from the data; only the wording comes from the model.
That is what separates this from the previous adapter, whose wording came from
templates the grader happened to reward.

Four kinds, deliberately mixed so the adapter learns discrimination rather than a
blanket habit of refusing:

``answerable``      a real entry, retrieved. Most of the set, because an adapter
                    that refuses everything scores 100% on abstention and ruins
                    everything else.
``nonexistent``     an invented but plausible name.
``false_mechanic``  a premise borrowed from another system. The topic list is
                    disjoint from the holdout's by construction -- see EXCLUDED.
``withheld``        a real entry whose own chunk is kept out of the context.

Generated items are filtered before they are kept: a refusal item survives only
if the teacher actually refused, an answerable one only if the teacher named the
entry. Roughly a fifth are discarded, which is the point of checking.
"""

from __future__ import annotations

import argparse
import collections
import pathlib
import random
import re
import sys

import orjson

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "eval"))

# Present in the holdout's false-premise or legacy families. Training on these
# would be measuring the training set.
EXCLUDED = {
    "attunement", "death saving throw", "school of magic", "alignment", "short rest",
    "concentration", "extra attack", "ki point", "spell point", "proficiency bonus",
    "wisdom save", "passive perception", "uncanny dodge", "experience point",
    "flat-footed", "magic missile", "mage armor", "magic weapon",
    "attack of opportunity", "power attack", "ability score", "spell level",
    "hero point", "positive energy", "evocation", "chill touch", "resurrect",
}

# Premises borrowed from other systems, none of which appear in the holdout.
FALSE_MECHANICS = [
    "bardic inspiration dice", "rage points for a barbarian", "action surge",
    "second wind healing", "divine smite on a hit", "warlock invocations",
    "sorcery points and metamagic", "channel divinity uses per rest",
    "expertise doubling a skill bonus", "a material component pouch costing gold",
    "inspiration from the GM", "carrying capacity measured in pounds",
    "adding proficiency to damage rolls", "a d20 advantage roll",
    "cantrips scaling at 5th, 11th and 17th level", "hit dice spent to heal",
    "a bonus action to attack with an offhand weapon", "counterspell as a reaction",
    "concentration on two spells at once", "a lucky feat to reroll dice",
    "bounded accuracy capping bonuses", "attack rolls against a flat-footed target using advantage",
    "spell slots recovered on an arcane recovery feature", "a familiar sharing its senses via a bonus action",
    "temporary hit points stacking from two sources", "a death domain cleric channelling negative energy",
    "sneak attack triggered by advantage", "a rogue's cunning action to dash",
    "wild shape uses per short rest", "a paladin's aura of protection adding Charisma to saves",
]

QUESTION_SYSTEM = (
    "You write questions the way a Pathfinder 2e player would actually ask them at a table: "
    "casual, specific to a situation, often describing something rather than naming it. "
    "Reply with the question only. One sentence or two. No preamble, no quotation marks."
)

RE_NAME = re.compile(r"[^a-z0-9 ]+")
REFUSAL_MARKERS = (
    "does not exist", "doesn't exist", "no such", "not a pathfinder", "cannot find",
    "can't find", "unable to find", "not aware of", "no record", "not in the excerpts",
    "do not include", "don't include", "not among", "no entry", "isn't a", "is not a",
    "not appear", "no mention",
)


def looks_like_refusal(text: str) -> bool:
    low = (text or "").lower()
    return any(m in low for m in REFUSAL_MARKERS)


def excluded(text: str) -> bool:
    low = (text or "").lower()
    return any(term in low for term in EXCLUDED)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--teacher", default="Qwen/Qwen3.8-27B")
    ap.add_argument("--chunks", type=pathlib.Path,
                    default=ROOT / "data" / "processed" / "aon_chunks.jsonl")
    ap.add_argument("--out", type=pathlib.Path,
                    default=ROOT / "data" / "processed" / "abstention_train.jsonl")
    ap.add_argument("--answerable", type=int, default=520)
    ap.add_argument("--nonexistent", type=int, default=240)
    ap.add_argument("--false-mechanic", type=int, default=180)
    ap.add_argument("--withheld", type=int, default=180)
    ap.add_argument("--k", type=int, default=8)
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--answer-batch-size", type=int, default=2,
                    help="answers carry eight excerpts; the 27B needs a smaller batch")
    ap.add_argument("--seed", type=int, default=17)
    ap.add_argument("--dump-answers", help="write every raw answer before filtering")
    args = ap.parse_args()

    import torch
    from transformers import AutoTokenizer, BitsAndBytesConfig
    from run_eval import SYSTEM_RAG, _load_hf, attach_context, format_context, strip_thinking

    rows = [orjson.loads(l) for l in args.chunks.open("rb")]
    by_id = {r["id"]: r for r in rows}

    # Hygiene: nothing the holdout or the generated benchmark touches.
    banned_ids, banned_names = set(), set()
    for bench in ("benchmark.jsonl", "holdout.jsonl"):
        path = ROOT / "eval" / bench
        if not path.exists():
            continue
        for line in path.open("rb"):
            item = orjson.loads(line)
            for sid in item["source_ids"] + (item.get("alt_source_ids") or []):
                banned_ids.add(sid)
                if sid in by_id and by_id[sid]["name"]:
                    banned_names.add(by_id[sid]["name"].lower())
    print(f"excluded {len(banned_ids)} eval chunks / {len(banned_names)} names")

    counts = collections.Counter(r["name"] for r in rows if r["name"])
    pool = [r for r in rows
            if r["name"] and counts[r["name"]] == 1 and r["id"] not in banned_ids
            and r["name"].lower() not in banned_names
            and r["remaster_status"] != "legacy" and r["summary"]
            and r["category"] in ("feat", "spell", "action", "condition", "equipment",
                                  "creature", "weapon", "hazard", "archetype")]
    print(f"{len(pool):,} eligible entries")

    rng = random.Random(args.seed)
    tok = AutoTokenizer.from_pretrained(args.teacher, padding_side="left")
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    quant = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                              bnb_4bit_compute_dtype=torch.bfloat16,
                              bnb_4bit_use_double_quant=True)
    model = _load_hf(args.teacher, quant)
    model.eval()
    device = next(model.parameters()).device

    def generate(pairs: list[tuple[str, str]], max_tokens: int,
                 batch_size: int | None = None) -> list[str]:
        # Answer prompts carry eight excerpts and run to several thousand tokens;
        # the 27B OOMs at the batch size that is fine for one-line question prompts.
        batch_size = batch_size or args.batch_size
        out: list[str] = []
        for start in range(0, len(pairs), batch_size):
            batch = pairs[start:start + batch_size]
            prompts = [tok.apply_chat_template(
                [{"role": "system", "content": sysmsg}, {"role": "user", "content": user}],
                tokenize=False, add_generation_prompt=True, enable_thinking=False)
                for sysmsg, user in batch]
            enc = tok(prompts, return_tensors="pt", padding=True).to(device)
            with torch.inference_mode():
                gen = model.generate(**enc, max_new_tokens=max_tokens, do_sample=False,
                                     temperature=None, top_p=None, top_k=None,
                                     pad_token_id=tok.pad_token_id)
            for seq in gen:
                text = tok.decode(seq[enc["input_ids"].shape[1]:], skip_special_tokens=True)
                out.append(strip_thinking(text))
            print(f"    {min(start + batch_size, len(pairs))}/{len(pairs)}", flush=True)
        return out

    # --- 1. questions ---------------------------------------------------------
    specs: list[dict] = []

    def ask_for_question(instruction: str) -> tuple[str, str]:
        return (QUESTION_SYSTEM, instruction)

    picks = rng.sample(pool, min(args.answerable + args.withheld, len(pool)))
    answerable_picks = picks[:args.answerable]
    withheld_picks = picks[args.answerable:]

    prompts = []
    for r in answerable_picks:
        style = rng.choice([
            "Describe it without naming it, as a player hunting for the right option.",
            "Ask about it by name, casually.",
            "Ask what happens in a specific situation where it would come up.",
        ])
        prompts.append(ask_for_question(
            f"A Pathfinder 2e {r['category'].replace('-', ' ')} called {r['name']}: "
            f"{r['summary']}\n\nWrite a player's question this entry answers. {style}"))
        specs.append({"kind": "answerable", "chunk": r})
    for r in withheld_picks:
        prompts.append(ask_for_question(
            f"A Pathfinder 2e {r['category'].replace('-', ' ')} called {r['name']}: "
            f"{r['summary']}\n\nWrite a player's question about it, naming it."))
        specs.append({"kind": "withheld", "chunk": r})

    real = {r["name"].lower() for r in rows if r["name"]}
    heads = sorted({r["name"].split(" ", 1)[0] for r in pool
                    if r["category"] == "feat" and " " in r["name"]})
    tails = sorted({r["name"].split(" ", 1)[1] for r in pool
                    if r["category"] == "feat" and " " in r["name"]})
    invented: set[str] = set()
    while len(invented) < args.nonexistent:
        name = f"{rng.choice(heads)} {rng.choice(tails)}"
        if name.lower() not in real and not excluded(name):
            invented.add(name)
    for name in sorted(invented):
        kind = rng.choice(["feat", "spell", "action"])
        prompts.append(ask_for_question(
            f"Write a player's question that asks about a Pathfinder 2e {kind} called "
            f"'{name}' — its level, prerequisites or what it does. Assume it is real."))
        specs.append({"kind": "nonexistent", "name": name})

    mechanics = [m for m in FALSE_MECHANICS if not excluded(m)]
    for i in range(args.false_mechanic):
        m = mechanics[i % len(mechanics)]
        prompts.append(ask_for_question(
            f"Write a player's question about Pathfinder 2e that wrongly assumes the game has "
            f"'{m}'. The player believes it exists. Vary the phrasing."))
        specs.append({"kind": "false_mechanic", "mechanic": m})

    print(f"\ngenerating {len(prompts)} questions with {args.teacher}")
    questions = generate(prompts, 70)
    for spec, q in zip(specs, questions):
        spec["question"] = " ".join(q.strip().strip('"').split())[:300]
    specs = [s for s in specs if 15 < len(s["question"]) < 300 and not excluded(s["question"])]
    print(f"{len(specs)} questions kept after length and topic filters")

    # --- 2. retrieve, using the deployed pipeline -----------------------------
    items = [{"question": s["question"], "id": str(i), "family": s["kind"]}
             for i, s in enumerate(specs)]
    import rewrite_queries  # noqa: F401  (ensures the module path resolves)
    from pf2etune import retrieval as R
    import retrieval_eval

    # Rewrites for these questions do not exist yet; generate them with the teacher.
    print("\ngenerating query rewrites")
    rw_prompts = [(rewrite_queries.SYSTEM, f"Question: {s['question']}") for s in specs]
    rewrites_raw = generate(rw_prompts, 90)
    rewrite_map = {s["question"]: rewrite_queries.parse(t)
                   for s, t in zip(specs, rewrites_raw)}
    cache_path = ROOT / "data" / "processed" / "query_rewrites.json"
    cache = orjson.loads(cache_path.read_bytes()) if cache_path.exists() else {}
    for q, v in rewrite_map.items():
        cache[f"{args.teacher}|{q}"] = v
    cache_path.write_bytes(orjson.dumps(cache, option=orjson.OPT_INDENT_2))

    attach_context(items, "Qwen/Qwen3-Embedding-0.6B", "hybrid3+hyde+cat+hop",
                   args.k, 1600, args.teacher)

    bodies = {r["id"]: r["text"] for r in rows}
    for spec, item in zip(specs, items):
        if spec["kind"] == "withheld":
            gold = spec["chunk"]["id"]
            keep = [cid for cid in item["retrieved"] if cid != gold][:args.k]
            hits = [(cid, next(m for m in [{"name": by_id[cid]["name"],
                                            "category": by_id[cid]["category"],
                                            "level": by_id[cid]["level"],
                                            "url": by_id[cid]["url"]}]))
                    for cid in keep]
            item["prompt"] = (format_context(hits, bodies, 1600)
                              + "\n\nQuestion: " + spec["question"])
            item["retrieved"] = keep

    # --- 3. answers: distilled where the premise holds, guided where it does not
    refusal_kinds = {"nonexistent", "withheld", "false_mechanic"}
    reason = {
        "nonexistent": ("The thing the player asks about does not exist in Pathfinder 2e. "
                        "No entry with that name has ever been published."),
        "withheld": ("The thing the player asks about is real, but its entry is not among "
                     "the excerpts provided, so its details cannot be confirmed from them."),
        "false_mechanic": ("The player's question assumes a rule that Pathfinder 2e does not "
                           "have; it belongs to a different game."),
    }
    GUIDE = (
        "You are answering a Pathfinder 2e rules question. {reason}\n\n"
        "Write the reply. Say plainly that it does not exist or is not in the excerpts, in your "
        "own words — vary the phrasing, do not use a stock sentence. Where the excerpts contain "
        "something genuinely relevant, say briefly what they do cover and cite its URL. Where the "
        "question assumes a rule from another game, name what Pathfinder 2e uses instead if the "
        "excerpts support it. Never invent a level, prerequisite or rules text. Two to four "
        "sentences."
    )

    print("\ngenerating answers")
    pairs = []
    for spec, item in zip(specs, items):
        if spec["kind"] in refusal_kinds:
            pairs.append((GUIDE.format(reason=reason[spec["kind"]]), item["prompt"]))
        else:
            pairs.append((SYSTEM_RAG, item["prompt"]))
    answers = generate(pairs, 400, batch_size=args.answer_batch_size)

    if args.dump_answers:
        pathlib.Path(args.dump_answers).write_bytes(orjson.dumps(
            [{"kind": s_["kind"], "question": s_["question"], "answer": a}
             for s_, a in zip(specs, answers)], option=orjson.OPT_INDENT_2))
        print(f"dumped raw answers -> {args.dump_answers}")

    kept, dropped = [], collections.Counter()
    for spec, item, answer in zip(specs, items, answers):
        answer = answer.strip()
        if not 20 < len(answer) < 2000:
            dropped[spec["kind"] + ":length"] += 1
            continue
        refused = looks_like_refusal(answer)
        if spec["kind"] in refusal_kinds:
            if not refused:
                dropped[spec["kind"] + ":did-not-refuse"] += 1
                continue
            # A guided refusal that invents a level defeats the purpose.
            if re.search(r"\blevel\s+\d{1,2}\b", answer, re.I) and spec["kind"] != "withheld":
                dropped[spec["kind"] + ":invented-a-level"] += 1
                continue
        else:
            name = spec["chunk"]["name"]
            if name.lower() not in answer.lower():
                dropped["answerable:did-not-name-entry"] += 1
                continue
            if refused:
                dropped["answerable:refused"] += 1
                continue
        kept.append({
            "kind": spec["kind"],
            "question": spec["question"],
            # The stored system prompt is always the inference-time one. The guide
            # was scaffolding for the teacher and must not appear in training.
            "messages": [{"role": "system", "content": SYSTEM_RAG},
                         {"role": "user", "content": item["prompt"]},
                         {"role": "assistant", "content": answer}],
            "gold_id": spec.get("chunk", {}).get("id") if spec.get("chunk") else None,
            "context_ids": item["retrieved"],
        })

    rng.shuffle(kept)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("wb") as fh:
        for row in kept:
            fh.write(orjson.dumps(row))
            fh.write(b"\n")

    kinds = collections.Counter(r["kind"] for r in kept)
    chars = sum(len(m["content"]) for r in kept for m in r["messages"])
    print(f"\nwrote {len(kept):,} items -> {args.out}")
    for k, v in kinds.most_common():
        print(f"  {k:16s} {v:5d}")
    print(f"  ~{chars / 4 / 1e6:.1f} M tokens, {chars / max(len(kept), 1) / 4:.0f} per item")
    refusal = sum(v for k, v in kinds.items() if k != "answerable")
    print(f"  {refusal / max(len(kept), 1):.0%} teach refusal")
    print("\ndropped by the quality filter:")
    for k, v in dropped.most_common():
        print(f"  {k:34s} {v:4d}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
