#!/usr/bin/env python3
"""Training data for the one behaviour retrieval cannot fix: knowing when to stop.

The deployed system answers hand-written questions at 85.3%, and its weakest
family is questions whose premise is false -- a feat nobody wrote, a mechanic
from a different game. It invents an answer about one time in five.

The previous adapter failed at exactly this, and the failure is instructive. It
was trained on templated questions with templated answers, gained ten points on a
benchmark generated by the same templates, and lost three on questions written by
hand. So this recipe changes both halves:

**Questions are written by a model, in player language, and never templated.**

Answers are handled in two passes, because the first attempt at pure distillation
failed in an informative way: asked the same question the student gets, the 27B
teacher **refused only 2 of 31 times** on premises that were false by
construction. It invents an answer just as the 9B does, so there is nothing to
distil. Frontier-scale models behave the same way, and the literature agrees --
RefusalBench finds refusal accuracy below 50% across thirty models, with neither
scale nor reasoning helping.

So answerable items are distilled from the teacher answering the real retrieved
context, and refusal items are *guided*: the teacher is told the verdict, which is
correct by construction, and asked to phrase it naturally against the same
excerpts. The label comes from the data; only the wording comes from the model.
That is what separates this from the previous adapter, whose wording came from
templates the grader happened to reward.

Four kinds, deliberately mixed so the adapter learns discrimination rather than a
blanket habit of refusing:

``answerable``      a real entry, retrieved. Most of the set, because an adapter
                    that refuses everything scores 100% on abstention and ruins
                    everything else.
``nonexistent``     an invented but plausible name.
``false_mechanic``  a premise borrowed from another system. The topic list is
                    disjoint from the holdout's by construction -- see EXCLUDED.
``withheld``        a real entry whose own chunk is kept out of the context.

Generated items are filtered before they are kept: a refusal item survives only
if the teacher actually refused, an answerable one only if the teacher named the
entry. Roughly a fifth are discarded, which is the point of checking.

The teacher is loaded here in 4-bit by default. ``--teacher-url`` sends its
prompts to an OpenAI-compatible server instead (vLLM, or Ollama at
``http://localhost:11434/v1``), all of them in flight at once, which is several
times faster than decoding two at a time out of bitsandbytes.
"""

from __future__ import annotations

import argparse
import collections
import os
import pathlib
import random
import re
import sys
import time

import orjson

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "eval"))

# Present in the holdout's false-premise or legacy families. Training on these
# would be measuring the training set.
EXCLUDED = {
    "attunement", "death saving throw", "school of magic", "alignment", "short rest",
    "concentration", "extra attack", "ki point", "spell point", "proficiency bonus",
    "wisdom save", "passive perception", "uncanny dodge", "experience point",
    "flat-footed", "magic missile", "mage armor", "magic weapon",
    "attack of opportunity", "power attack", "ability score", "spell level",
    "hero point", "positive energy", "evocation", "chill touch", "resurrect",
}

# Premises borrowed from other systems, none of which appear in the holdout.
FALSE_MECHANICS = [
    "bardic inspiration dice", "rage points for a barbarian", "action surge",
    "second wind healing", "divine smite on a hit", "warlock invocations",
    "sorcery points and metamagic", "channel divinity uses per rest",
    "expertise doubling a skill bonus", "a material component pouch costing gold",
    "inspiration from the GM", "carrying capacity measured in pounds",
    "adding proficiency to damage rolls", "a d20 advantage roll",
    "cantrips scaling at 5th, 11th and 17th level", "hit dice spent to heal",
    "a bonus action to attack with an offhand weapon", "counterspell as a reaction",
    "concentration on two spells at once", "a lucky feat to reroll dice",
    "bounded accuracy capping bonuses", "attack rolls against a flat-footed target using advantage",
    "spell slots recovered on an arcane recovery feature", "a familiar sharing its senses via a bonus action",
    "temporary hit points stacking from two sources", "a death domain cleric channelling negative energy",
    "sneak attack triggered by advantage", "a rogue's cunning action to dash",
    "wild shape uses per short rest", "a paladin's aura of protection adding Charisma to saves",
]

QUESTION_SYSTEM = (
    "You write questions the way a Pathfinder 2e player would actually ask them at a table: "
    "casual, specific to a situation, often describing something rather than naming it. "
    "Reply with the question only. One sentence or two. No preamble, no quotation marks."
)

# A false-mechanic item is good when the teacher *corrects* the premise rather
# than refusing outright: "Pathfinder 2e has no bardic inspiration dice; bards use
# spell slots and a muse." The evaluator's refusal detector is anchored on
# existence and presence, so it misses most of these. This is anchored on the
# system being denied the mechanic, or the mechanic being placed in another game.
RE_CORRECTS = re.compile(
    r"\b(?:pathfinder|pf2e?|2e|this game|this system|the game|the system)\b[^.;]{0,40}?"
    r"\b(?:has no|have no|does not have|doesn't have|does not use|doesn't use|lacks|"
    r"does not include|doesn't include|has nothing|does not feature|doesn't feature)\b"
    r"|\b(?:is|are|isn't|aren't|is not|are not)\s+(?:a|an)?\s*"
    r"(?:pathfinder|pf2e?|2e)\b[^.;]{0,20}?\b(?:mechanic|rule|concept|feature|thing|term)\b"
    r"|\b(?:not|isn't|aren't|is not|are not|no)\s+(?:a\s+|an\s+)?(?:part of|feature of|thing in|"
    r"mechanic in|rule in|concept in|used in|present in|found in)\s+(?:pathfinder|pf2e?|2e|this)"
    r"|\b(?:from|belongs to|comes from|is part of|is a|is an|that's a|that is a)\b[^.;]{0,20}?"
    r"\b(?:d&d|dungeons\s*&\s*dragons|dungeons and dragons|5e|5th edition|fifth edition|"
    r"another game|a different game|other (?:game|system)s?|another system|a different system)\b"
    r"|\b(?:d&d|dungeons\s*&\s*dragons|5e|5th edition|fifth edition)\s+(?:mechanic|rule|concept|"
    r"feature|term|thing)\b"
    r"|\bno (?:such )?(?:mechanic|rule|concept|feature|system)\b",
    re.I)

# A refusal that nonetheless states the level of the thing that does not exist
# is a fabrication dressed as a refusal. Only an *assertion* of a level counts:
# "is a 4th-level feat", "Feat 6", "a level 3 spell". Mentions like "you cannot
# take it at 1st level or any other" are how a good refusal talks and must pass,
# so bare "level N" is not enough here (compare score.RE_LEVEL_CLAIM).
RE_ASSERTS_LEVEL = re.compile(
    r"\b(?:is|as|it's|its|being|was)\s+(?:a|an)\s+(?:\d{1,2}(?:st|nd|rd|th)[- ]level|level[- ]\d{1,2})\b"
    r"|\b(?:a|an|the)\s+(?:\d{1,2}(?:st|nd|rd|th)[- ]level|level[- ]\d{1,2})\s+"
    r"(?:feat|spell|item|creature|action|ritual|archetype|monster|weapon|hazard|ability)\b"
    r"|\b(?:feat|spell|item|creature|ritual|hazard)\s+\d{1,2}\b"
    r"|\brequires?\s+(?:you to be\s+)?level\s+\d{1,2}\b"
    r"|\b(?:available|unlocked|gained|taken)\s+at\s+(?:level\s+\d{1,2}|\d{1,2}(?:st|nd|rd|th)\s+level)\b",
    re.I)


def asserts_level_for(answer: str, name: str | None) -> bool:
    """Is a level asserted *about the thing that does not exist*?

    Clause by clause: the invented name and the level assertion must sit in
    the same clause, and that clause must not deny it. The trial run rejected
    "there is no feat called X; you are likely thinking of Y, which is a level
    18 feat", which is the best refusal there is -- it corrects the player.
    Without a name to anchor on, any asserted level counts.
    """
    import score
    if not name:
        return bool(RE_ASSERTS_LEVEL.search(answer))
    low = name.lower()
    for clause in re.split(r"[.;:!?\n]", answer):
        if (low in clause.lower() and RE_ASSERTS_LEVEL.search(clause)
                and not re.search(rf"\b(?:{score.RE_NEGATION})\b", clause, re.I)):
            return True
    return False


def api_generator(base_url: str, model: str, api_key: str = "", workers: int = 16,
                  client=None):
    """A ``generate(pairs, max_tokens)`` over an OpenAI-compatible chat endpoint.

    The transformers path below loads the 27B in 4-bit and decodes two
    prompts at a time; a server with continuous batching (vLLM, Ollama) does
    the same work several times faster, so the teacher can be whatever answers
    at ``base_url``. Every prompt is in flight at once, ``workers`` deep; the
    order of the results is the order of the prompts. Thinking is switched off
    where the server understands the request, and stripped where it does not.
    """
    import concurrent.futures

    import httpx
    from run_eval import strip_thinking

    url = base_url.rstrip("/") + "/chat/completions"
    headers = {"Authorization": f"Bearer {api_key}"} if api_key else {}
    client = client or httpx.Client(timeout=300.0)
    # Learned once from the server, then kept: which field names the token
    # budget, and whether it accepts the template switch for thinking.
    state = {"tokens": "max_tokens", "thinking": True}

    def one(pair: tuple[str, str], max_tokens: int) -> str:
        system, user = pair
        body: dict = {"model": model, "temperature": 0,
                      "messages": [{"role": "system", "content": system},
                                   {"role": "user", "content": user}]}
        last = ""
        for attempt in range(8):
            body.pop("max_tokens", None)
            body.pop("max_completion_tokens", None)
            body.pop("chat_template_kwargs", None)
            body[state["tokens"]] = max_tokens
            if state["thinking"]:
                body["chat_template_kwargs"] = {"enable_thinking": False}
            try:
                r = client.post(url, headers=headers, json=body)
            except httpx.HTTPError as exc:
                last = f"{type(exc).__name__}: {exc}"
                time.sleep(min(2 ** attempt, 60))
                continue
            if r.status_code == 400 and state["thinking"] and "chat_template_kwargs" in r.text:
                state["thinking"] = False
                continue
            if r.status_code == 400 and state["tokens"] == "max_tokens" and "max_tokens" in r.text:
                state["tokens"] = "max_completion_tokens"
                continue
            if r.status_code in (408, 409, 429, 500, 502, 503, 504, 529):
                last = f"HTTP {r.status_code}: {r.text[:200]}"
                time.sleep(min(2 ** attempt, 60))
                continue
            if r.status_code >= 400:
                raise RuntimeError(f"HTTP {r.status_code} on {user[:60]!r}: {r.text[:300]}")
            data = orjson.loads(r.content)
            return strip_thinking(data["choices"][0]["message"].get("content") or "")
        raise RuntimeError(f"giving up after 8 attempts on {user[:60]!r}; last: {last}")

    def generate(pairs: list[tuple[str, str]], max_tokens: int,
                 batch_size: int | None = None) -> list[str]:
        out: list[str] = []
        with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as pool:
            for text in pool.map(lambda pr: one(pr, max_tokens), pairs):
                out.append(text)
                if len(out) % 50 == 0 or len(out) == len(pairs):
                    print(f"    {len(out)}/{len(pairs)}", flush=True)
        return out

    return generate


def looks_like_refusal(text: str) -> bool:
    """Share the evaluator's detector rather than keeping a second one.

    The first version of this filter had its own phrase list and discarded most of
    the teacher's refusals, which is how the evaluator's identical bug came to
    light. One implementation, one set of regression tests.
    """
    import score
    return score.refuses(text)


def excluded(text: str) -> bool:
    low = (text or "").lower()
    return any(term in low for term in EXCLUDED)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--teacher", default="Qwen/Qwen3.8-27B",
                    help="HF model id to load here, or the model name the server at "
                         "--teacher-url knows it by")
    ap.add_argument("--teacher-url", default=None,
                    help="OpenAI-compatible base URL (vLLM, Ollama: http://localhost:11434/v1) "
                         "to send the teacher's prompts to instead of loading it here")
    ap.add_argument("--teacher-key-env", default="OPENAI_API_KEY",
                    help="environment variable holding the key for --teacher-url, if any")
    ap.add_argument("--workers", type=int, default=16,
                    help="prompts in flight at once against --teacher-url")
    ap.add_argument("--chunks", type=pathlib.Path,
                    default=ROOT / "data" / "processed" / "aon_chunks.jsonl")
    ap.add_argument("--out", type=pathlib.Path,
                    default=ROOT / "data" / "processed" / "abstention_train.jsonl")
    ap.add_argument("--answerable", type=int, default=520)
    ap.add_argument("--nonexistent", type=int, default=240)
    ap.add_argument("--false-mechanic", type=int, default=180)
    ap.add_argument("--withheld", type=int, default=180)
    ap.add_argument("--k", type=int, default=8)
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--answer-batch-size", type=int, default=2,
                    help="answers carry eight excerpts; the 27B needs a smaller batch")
    ap.add_argument("--seed", type=int, default=17)
    ap.add_argument("--dump-answers", help="write every raw answer before filtering")
    args = ap.parse_args()

    from run_eval import SYSTEM_RAG, attach_context, format_context
    if not args.teacher_url:
        import torch
        from run_eval import _load_hf, strip_thinking
        from transformers import AutoTokenizer, BitsAndBytesConfig

    rows = [orjson.loads(line) for line in args.chunks.open("rb")]
    by_id = {r["id"]: r for r in rows}

    # Hygiene: nothing the holdout or the generated benchmark touches.
    banned_ids, banned_names = set(), set()
    for bench in ("benchmark.jsonl", "holdout.jsonl"):
        path = ROOT / "eval" / bench
        if not path.exists():
            continue
        for line in path.open("rb"):
            item = orjson.loads(line)
            for sid in item["source_ids"] + (item.get("alt_source_ids") or []):
                banned_ids.add(sid)
                if sid in by_id and by_id[sid]["name"]:
                    banned_names.add(by_id[sid]["name"].lower())
    print(f"excluded {len(banned_ids)} eval chunks / {len(banned_names)} names")

    counts = collections.Counter(r["name"] for r in rows if r["name"])
    pool = [r for r in rows
            if r["name"] and counts[r["name"]] == 1 and r["id"] not in banned_ids
            and r["name"].lower() not in banned_names
            and r["remaster_status"] != "legacy" and r["summary"]
            and r["category"] in ("feat", "spell", "action", "condition", "equipment",
                                  "creature", "weapon", "hazard", "archetype")]
    print(f"{len(pool):,} eligible entries")

    rng = random.Random(args.seed)
    if args.teacher_url:
        generate = api_generator(args.teacher_url, args.teacher,
                                 os.environ.get(args.teacher_key_env, ""), args.workers)
        print(f"teacher   {args.teacher} at {args.teacher_url}, {args.workers} prompts in flight")
    else:
        tok = AutoTokenizer.from_pretrained(args.teacher, padding_side="left")
        if tok.pad_token is None:
            tok.pad_token = tok.eos_token
        quant = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                                  bnb_4bit_compute_dtype=torch.bfloat16,
                                  bnb_4bit_use_double_quant=True)
        model = _load_hf(args.teacher, quant)
        model.eval()
        device = next(model.parameters()).device

        def generate(pairs: list[tuple[str, str]], max_tokens: int,
                     batch_size: int | None = None) -> list[str]:
            # Answer prompts carry eight excerpts and run to several thousand
            # tokens; the 27B OOMs at the batch size that is fine for one-line
            # question prompts. Sorted by length so a batch pads as little as
            # possible; the results go back in the callers' order.
            batch_size = batch_size or args.batch_size
            order = sorted(range(len(pairs)), key=lambda i: len(pairs[i][0]) + len(pairs[i][1]))
            out: list[str] = [""] * len(pairs)
            for start in range(0, len(order), batch_size):
                idx = order[start:start + batch_size]
                prompts = [tok.apply_chat_template(
                    [{"role": "system", "content": pairs[i][0]},
                     {"role": "user", "content": pairs[i][1]}],
                    tokenize=False, add_generation_prompt=True, enable_thinking=False)
                    for i in idx]
                enc = tok(prompts, return_tensors="pt", padding=True).to(device)
                with torch.inference_mode():
                    gen = model.generate(**enc, max_new_tokens=max_tokens, do_sample=False,
                                         temperature=None, top_p=None, top_k=None,
                                         pad_token_id=tok.pad_token_id)
                for i, seq in zip(idx, gen, strict=True):
                    text = tok.decode(seq[enc["input_ids"].shape[1]:], skip_special_tokens=True)
                    out[i] = strip_thinking(text)
                print(f"    {min(start + batch_size, len(pairs))}/{len(pairs)}", flush=True)
            return out

    # --- 1. questions ---------------------------------------------------------
    specs: list[dict] = []

    def ask_for_question(instruction: str) -> tuple[str, str]:
        return (QUESTION_SYSTEM, instruction)

    picks = rng.sample(pool, min(args.answerable + args.withheld, len(pool)))
    answerable_picks = picks[:args.answerable]
    withheld_picks = picks[args.answerable:]

    prompts = []
    for r in answerable_picks:
        style = rng.choice([
            "Describe it without naming it, as a player hunting for the right option.",
            "Ask about it by name, casually.",
            "Ask what happens in a specific situation where it would come up.",
        ])
        prompts.append(ask_for_question(
            f"A Pathfinder 2e {r['category'].replace('-', ' ')} called {r['name']}: "
            f"{r['summary']}\n\nWrite a player's question this entry answers. {style}"))
        specs.append({"kind": "answerable", "chunk": r})
    for r in withheld_picks:
        prompts.append(ask_for_question(
            f"A Pathfinder 2e {r['category'].replace('-', ' ')} called {r['name']}: "
            f"{r['summary']}\n\nWrite a player's question about it, naming it."))
        specs.append({"kind": "withheld", "chunk": r})

    real = {r["name"].lower() for r in rows if r["name"]}
    heads = sorted({r["name"].split(" ", 1)[0] for r in pool
                    if r["category"] == "feat" and " " in r["name"]})
    tails = sorted({r["name"].split(" ", 1)[1] for r in pool
                    if r["category"] == "feat" and " " in r["name"]})
    invented: set[str] = set()
    while len(invented) < args.nonexistent:
        name = f"{rng.choice(heads)} {rng.choice(tails)}"
        if name.lower() not in real and not excluded(name):
            invented.add(name)
    for name in sorted(invented):
        kind = rng.choice(["feat", "spell", "action"])
        prompts.append(ask_for_question(
            f"Write a player's question that asks about a Pathfinder 2e {kind} called "
            f"'{name}' — its level, prerequisites or what it does. Assume it is real."))
        specs.append({"kind": "nonexistent", "name": name})

    mechanics = [m for m in FALSE_MECHANICS if not excluded(m)]
    for i in range(args.false_mechanic):
        m = mechanics[i % len(mechanics)]
        prompts.append(ask_for_question(
            f"Write a player's question about Pathfinder 2e that wrongly assumes the game has "
            f"'{m}'. The player believes it exists. Vary the phrasing."))
        specs.append({"kind": "false_mechanic", "mechanic": m})

    print(f"\ngenerating {len(prompts)} questions with {args.teacher}")
    questions = generate(prompts, 70)
    for spec, q in zip(specs, questions, strict=False):
        spec["question"] = " ".join(q.strip().strip('"').split())[:300]
    specs = [s for s in specs if 15 < len(s["question"]) < 300 and not excluded(s["question"])]
    print(f"{len(specs)} questions kept after length and topic filters")

    # --- 2. retrieve, using the deployed pipeline -----------------------------
    items = [{"question": s["question"], "id": str(i), "family": s["kind"]}
             for i, s in enumerate(specs)]
    import rewrite_queries


    # Rewrites for these questions do not exist yet; generate them with the teacher.
    print("\ngenerating query rewrites")
    rw_prompts = [(rewrite_queries.SYSTEM, f"Question: {s['question']}") for s in specs]
    rewrites_raw = generate(rw_prompts, 90)
    rewrite_map = {s["question"]: rewrite_queries.parse(t)
                   for s, t in zip(specs, rewrites_raw, strict=False)}
    cache_path = ROOT / "data" / "processed" / "query_rewrites.json"
    cache = orjson.loads(cache_path.read_bytes()) if cache_path.exists() else {}
    for q, v in rewrite_map.items():
        cache[f"{args.teacher}|{q}"] = v
    cache_path.write_bytes(orjson.dumps(cache, option=orjson.OPT_INDENT_2))

    attach_context(items, "Qwen/Qwen3-Embedding-0.6B", "hybrid3+hyde+cat+hop",
                   args.k, 1600, args.teacher)

    bodies = {r["id"]: r["text"] for r in rows}
    for spec, item in zip(specs, items, strict=False):
        if spec["kind"] == "withheld":
            gold = spec["chunk"]["id"]
            keep = [cid for cid in item["retrieved"] if cid != gold][:args.k]
            hits = [(cid, next(m for m in [{"name": by_id[cid]["name"],
                                            "category": by_id[cid]["category"],
                                            "level": by_id[cid]["level"],
                                            "url": by_id[cid]["url"]}]))
                    for cid in keep]
            item["prompt"] = (format_context(hits, bodies, 1600)
                              + "\n\nQuestion: " + spec["question"])
            item["retrieved"] = keep

    # --- 3. answers: distilled where the premise holds, guided where it does not
    refusal_kinds = {"nonexistent", "withheld", "false_mechanic"}
    reason = {
        "nonexistent": ("The thing the player asks about does not exist in Pathfinder 2e. "
                        "No entry with that name has ever been published."),
        "withheld": ("The thing the player asks about is real, but its entry is not among "
                     "the excerpts provided, so its details cannot be confirmed from them."),
        "false_mechanic": ("The player's question assumes a rule that Pathfinder 2e does not "
                           "have; it belongs to a different game."),
    }
    GUIDE = (
        "You are answering a Pathfinder 2e rules question. {reason}\n\n"
        "Write the reply. Say plainly that it does not exist or is not in the excerpts, in your "
        "own words — vary the phrasing, do not use a stock sentence. Where the excerpts contain "
        "something genuinely relevant, say briefly what they do cover and cite its URL. Where the "
        "question assumes a rule from another game, name what Pathfinder 2e uses instead if the "
        "excerpts support it. Never invent a level, prerequisite or rules text. Two to four "
        "sentences."
    )

    print("\ngenerating answers")
    pairs = []
    for spec, item in zip(specs, items, strict=False):
        if spec["kind"] in refusal_kinds:
            pairs.append((GUIDE.format(reason=reason[spec["kind"]]), item["prompt"]))
        else:
            pairs.append((SYSTEM_RAG, item["prompt"]))
    answers = generate(pairs, 400, batch_size=args.answer_batch_size)

    if args.dump_answers:
        pathlib.Path(args.dump_answers).write_bytes(orjson.dumps(
            [{"kind": s_["kind"], "question": s_["question"], "answer": a}
             for s_, a in zip(specs, answers, strict=False)], option=orjson.OPT_INDENT_2))
        print(f"dumped raw answers -> {args.dump_answers}")

    kept, dropped = [], collections.Counter()
    for spec, item, answer in zip(specs, items, answers, strict=False):
        answer = answer.strip()
        if not 20 < len(answer) < 2000:
            dropped[spec["kind"] + ":length"] += 1
            continue
        refused = looks_like_refusal(answer)
        if spec["kind"] == "false_mechanic":
            # The target behaviour here is correction, not refusal: "Pathfinder 2e
            # has no bardic inspiration dice; bards use spell slots and a muse."
            # Requiring a refusal phrase discarded most of them.
            refused = refused or bool(RE_CORRECTS.search(answer))
        if spec["kind"] in refusal_kinds:
            if not refused:
                dropped[spec["kind"] + ":did-not-refuse"] += 1
                continue
            # Reject only an *asserted* level for the thing that does not exist.
            # A good refusal often mentions levels legitimately -- "you cannot take
            # it at 1st level or any other" -- and the first version of this rule
            # threw away ten of twelve good examples for saying so.
            if spec["kind"] != "withheld" and asserts_level_for(
                    answer, spec.get("name") or spec.get("mechanic")):
                dropped[spec["kind"] + ":asserted-a-level"] += 1
                continue
        else:
            name = spec["chunk"]["name"]
            if name.lower() not in answer.lower():
                dropped["answerable:did-not-name-entry"] += 1
                continue
            if refused:
                dropped["answerable:refused"] += 1
                continue
        kept.append({
            "kind": spec["kind"],
            "question": spec["question"],
            # The stored system prompt is always the inference-time one. The guide
            # was scaffolding for the teacher and must not appear in training.
            "messages": [{"role": "system", "content": SYSTEM_RAG},
                         {"role": "user", "content": item["prompt"]},
                         {"role": "assistant", "content": answer}],
            "gold_id": spec.get("chunk", {}).get("id") if spec.get("chunk") else None,
            "context_ids": item["retrieved"],
        })

    rng.shuffle(kept)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("wb") as fh:
        for row in kept:
            fh.write(orjson.dumps(row))
            fh.write(b"\n")

    kinds = collections.Counter(r["kind"] for r in kept)
    chars = sum(len(m["content"]) for r in kept for m in r["messages"])
    print(f"\nwrote {len(kept):,} items -> {args.out}")
    for k, v in kinds.most_common():
        print(f"  {k:16s} {v:5d}")
    print(f"  ~{chars / 4 / 1e6:.1f} M tokens, {chars / max(len(kept), 1) / 4:.0f} per item")
    refusal = sum(v for k, v in kinds.items() if k != "answerable")
    print(f"  {refusal / max(len(kept), 1):.0%} teach refusal")
    print("\ndropped by the quality filter:")
    for k, v in dropped.most_common():
        print(f"  {k:34s} {v:4d}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
